void KNN_cuts_vs_GEN_pT()
{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Thu Mar  2 22:31:44 2017) by ROOT version6.06/02
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",393,94,708,534);
   gStyle->SetOptFit(1);
   Canvas_1->Range(-5.125,-2.75625,56.125,24.80625);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetGridx();
   Canvas_1->SetGridy();
   Canvas_1->SetFrameBorderMode(0);
   Canvas_1->SetFrameBorderMode(0);
   
   TProfile *KNN_cuts_vs_Gen_pT = new TProfile("KNN_cuts_vs_Gen_pT","KNN cuts versus GEN pT",49,1,50,"");
   KNN_cuts_vs_Gen_pT->SetBinEntries(1,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(2,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(3,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(4,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(5,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(6,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(7,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(8,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(9,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(10,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(11,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(12,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(13,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(14,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(15,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(16,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(17,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(18,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(19,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(20,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(21,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(22,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(23,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(24,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(25,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(26,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(27,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(28,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(29,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(30,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(31,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(32,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(33,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(34,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(35,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(36,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(37,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(38,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(39,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(40,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(41,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(42,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(43,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(44,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(45,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(46,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(47,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(48,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(49,1);
   KNN_cuts_vs_Gen_pT->SetBinEntries(50,10);
   KNN_cuts_vs_Gen_pT->SetBinContent(1,1);
   KNN_cuts_vs_Gen_pT->SetBinContent(2,1);
   KNN_cuts_vs_Gen_pT->SetBinContent(3,2);
   KNN_cuts_vs_Gen_pT->SetBinContent(4,3);
   KNN_cuts_vs_Gen_pT->SetBinContent(5,4);
   KNN_cuts_vs_Gen_pT->SetBinContent(6,4);
   KNN_cuts_vs_Gen_pT->SetBinContent(7,5);
   KNN_cuts_vs_Gen_pT->SetBinContent(8,5);
   KNN_cuts_vs_Gen_pT->SetBinContent(9,6);
   KNN_cuts_vs_Gen_pT->SetBinContent(10,7);
   KNN_cuts_vs_Gen_pT->SetBinContent(11,7);
   KNN_cuts_vs_Gen_pT->SetBinContent(12,8);
   KNN_cuts_vs_Gen_pT->SetBinContent(13,8);
   KNN_cuts_vs_Gen_pT->SetBinContent(14,9);
   KNN_cuts_vs_Gen_pT->SetBinContent(15,9);
   KNN_cuts_vs_Gen_pT->SetBinContent(16,10);
   KNN_cuts_vs_Gen_pT->SetBinContent(17,10);
   KNN_cuts_vs_Gen_pT->SetBinContent(18,10);
   KNN_cuts_vs_Gen_pT->SetBinContent(19,11);
   KNN_cuts_vs_Gen_pT->SetBinContent(20,11);
   KNN_cuts_vs_Gen_pT->SetBinContent(21,12);
   KNN_cuts_vs_Gen_pT->SetBinContent(22,12);
   KNN_cuts_vs_Gen_pT->SetBinContent(23,13);
   KNN_cuts_vs_Gen_pT->SetBinContent(24,13);
   KNN_cuts_vs_Gen_pT->SetBinContent(25,13);
   KNN_cuts_vs_Gen_pT->SetBinContent(26,14);
   KNN_cuts_vs_Gen_pT->SetBinContent(27,14);
   KNN_cuts_vs_Gen_pT->SetBinContent(28,15);
   KNN_cuts_vs_Gen_pT->SetBinContent(29,14);
   KNN_cuts_vs_Gen_pT->SetBinContent(30,15);
   KNN_cuts_vs_Gen_pT->SetBinContent(31,16);
   KNN_cuts_vs_Gen_pT->SetBinContent(32,15);
   KNN_cuts_vs_Gen_pT->SetBinContent(33,16);
   KNN_cuts_vs_Gen_pT->SetBinContent(34,17);
   KNN_cuts_vs_Gen_pT->SetBinContent(35,16);
   KNN_cuts_vs_Gen_pT->SetBinContent(36,17);
   KNN_cuts_vs_Gen_pT->SetBinContent(37,17);
   KNN_cuts_vs_Gen_pT->SetBinContent(38,17);
   KNN_cuts_vs_Gen_pT->SetBinContent(39,16);
   KNN_cuts_vs_Gen_pT->SetBinContent(40,17);
   KNN_cuts_vs_Gen_pT->SetBinContent(41,18);
   KNN_cuts_vs_Gen_pT->SetBinContent(42,19);
   KNN_cuts_vs_Gen_pT->SetBinContent(43,17);
   KNN_cuts_vs_Gen_pT->SetBinContent(44,21);
   KNN_cuts_vs_Gen_pT->SetBinContent(45,18);
   KNN_cuts_vs_Gen_pT->SetBinContent(46,18);
   KNN_cuts_vs_Gen_pT->SetBinContent(47,19);
   KNN_cuts_vs_Gen_pT->SetBinContent(48,18);
   KNN_cuts_vs_Gen_pT->SetBinContent(49,18);
   KNN_cuts_vs_Gen_pT->SetBinContent(50,311);
   KNN_cuts_vs_Gen_pT->SetBinError(1,1);
   KNN_cuts_vs_Gen_pT->SetBinError(2,1);
   KNN_cuts_vs_Gen_pT->SetBinError(3,2);
   KNN_cuts_vs_Gen_pT->SetBinError(4,3);
   KNN_cuts_vs_Gen_pT->SetBinError(5,4);
   KNN_cuts_vs_Gen_pT->SetBinError(6,4);
   KNN_cuts_vs_Gen_pT->SetBinError(7,5);
   KNN_cuts_vs_Gen_pT->SetBinError(8,5);
   KNN_cuts_vs_Gen_pT->SetBinError(9,6);
   KNN_cuts_vs_Gen_pT->SetBinError(10,7);
   KNN_cuts_vs_Gen_pT->SetBinError(11,7);
   KNN_cuts_vs_Gen_pT->SetBinError(12,8);
   KNN_cuts_vs_Gen_pT->SetBinError(13,8);
   KNN_cuts_vs_Gen_pT->SetBinError(14,9);
   KNN_cuts_vs_Gen_pT->SetBinError(15,9);
   KNN_cuts_vs_Gen_pT->SetBinError(16,10);
   KNN_cuts_vs_Gen_pT->SetBinError(17,10);
   KNN_cuts_vs_Gen_pT->SetBinError(18,10);
   KNN_cuts_vs_Gen_pT->SetBinError(19,11);
   KNN_cuts_vs_Gen_pT->SetBinError(20,11);
   KNN_cuts_vs_Gen_pT->SetBinError(21,12);
   KNN_cuts_vs_Gen_pT->SetBinError(22,12);
   KNN_cuts_vs_Gen_pT->SetBinError(23,13);
   KNN_cuts_vs_Gen_pT->SetBinError(24,13);
   KNN_cuts_vs_Gen_pT->SetBinError(25,13);
   KNN_cuts_vs_Gen_pT->SetBinError(26,14);
   KNN_cuts_vs_Gen_pT->SetBinError(27,14);
   KNN_cuts_vs_Gen_pT->SetBinError(28,15);
   KNN_cuts_vs_Gen_pT->SetBinError(29,14);
   KNN_cuts_vs_Gen_pT->SetBinError(30,15);
   KNN_cuts_vs_Gen_pT->SetBinError(31,16);
   KNN_cuts_vs_Gen_pT->SetBinError(32,15);
   KNN_cuts_vs_Gen_pT->SetBinError(33,16);
   KNN_cuts_vs_Gen_pT->SetBinError(34,17);
   KNN_cuts_vs_Gen_pT->SetBinError(35,16);
   KNN_cuts_vs_Gen_pT->SetBinError(36,17);
   KNN_cuts_vs_Gen_pT->SetBinError(37,17);
   KNN_cuts_vs_Gen_pT->SetBinError(38,17);
   KNN_cuts_vs_Gen_pT->SetBinError(39,16);
   KNN_cuts_vs_Gen_pT->SetBinError(40,17);
   KNN_cuts_vs_Gen_pT->SetBinError(41,18);
   KNN_cuts_vs_Gen_pT->SetBinError(42,19);
   KNN_cuts_vs_Gen_pT->SetBinError(43,17);
   KNN_cuts_vs_Gen_pT->SetBinError(44,21);
   KNN_cuts_vs_Gen_pT->SetBinError(45,18);
   KNN_cuts_vs_Gen_pT->SetBinError(46,18);
   KNN_cuts_vs_Gen_pT->SetBinError(47,19);
   KNN_cuts_vs_Gen_pT->SetBinError(48,18);
   KNN_cuts_vs_Gen_pT->SetBinError(49,18);
   KNN_cuts_vs_Gen_pT->SetBinError(50,102.6401);
   KNN_cuts_vs_Gen_pT->SetEntries(59);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.615,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *AText = ptstats->AddText("KNN_cuts_vs_Gen_pT");
   AText->SetTextSize(0.04906667);
   AText = ptstats->AddText("Entries = 59     ");
   AText = ptstats->AddText("Mean  =     25");
   AText = ptstats->AddText("Mean y =  12.16");
   AText = ptstats->AddText("Std Dev   =  14.14");
   AText = ptstats->AddText("Std Dev y =  5.369");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(111);
   ptstats->Draw();
   KNN_cuts_vs_Gen_pT->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(KNN_cuts_vs_Gen_pT);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   KNN_cuts_vs_Gen_pT->SetLineColor(ci);
   KNN_cuts_vs_Gen_pT->GetXaxis()->SetLabelFont(42);
   KNN_cuts_vs_Gen_pT->GetXaxis()->SetLabelSize(0.035);
   KNN_cuts_vs_Gen_pT->GetXaxis()->SetTitleSize(0.035);
   KNN_cuts_vs_Gen_pT->GetXaxis()->SetTitleFont(42);
   KNN_cuts_vs_Gen_pT->GetYaxis()->SetLabelFont(42);
   KNN_cuts_vs_Gen_pT->GetYaxis()->SetLabelSize(0.035);
   KNN_cuts_vs_Gen_pT->GetYaxis()->SetTitleSize(0.035);
   KNN_cuts_vs_Gen_pT->GetYaxis()->SetTitleFont(42);
   KNN_cuts_vs_Gen_pT->GetZaxis()->SetLabelFont(42);
   KNN_cuts_vs_Gen_pT->GetZaxis()->SetLabelSize(0.035);
   KNN_cuts_vs_Gen_pT->GetZaxis()->SetTitleSize(0.035);
   KNN_cuts_vs_Gen_pT->GetZaxis()->SetTitleFont(42);
   KNN_cuts_vs_Gen_pT->Draw("");
   
   TPaveText *pt = new TPaveText(0.3072531,0.9363534,0.6927469,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   AText = pt->AddText("KNN cuts versus GEN pT");
   pt->Draw();
   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
